globalThis.JEV_FILTER_PRESETS = [
  {
    id: "video_games",
    label: "Video games",
    description: "Gameplay, game news, guides, streams, and gaming culture.",
    question: "Is this video primarily about video games, gameplay, gaming news, game guides, game streams, or gaming culture?",
  },
  {
    id: "tv_movie_clips",
    label: "TV and movie clips",
    description: "Scenes, excerpts, edits, and compilations from scripted shows or films.",
    question: "Would this video's main content itself consist of footage or scenes from a scripted television show or movie? Answer yes for clips, compilations, scene edits, excerpts, and fan-channel uploads. When a channel is named after a show or film franchise and the title describes something happening to or involving its fictional characters, answer yes even if the title is phrased as a question. Answer no when the main content is someone discussing, explaining, evaluating, ranking, reviewing, reacting to, or reporting on the work.",
  },
  {
    id: "celebrity_gossip",
    label: "Celebrity gossip",
    description: "Rumors and personal-life coverage about celebrities.",
    question: "Is this video primarily celebrity gossip, rumors, relationship speculation, or coverage of a celebrity's private life?",
  },
  {
    id: "influencer_drama",
    label: "Influencer drama",
    description: "Feuds, callouts, cancellations, and creator controversies.",
    question: "Is this video primarily about influencer or creator drama, feuds, callouts, cancellations, apologies, or interpersonal controversy?",
  },
  {
    id: "ragebait",
    label: "Ragebait and outrage",
    description: "Content designed mainly to provoke anger or disgust.",
    question: "Is this video primarily ragebait or outrage content designed to provoke anger, disgust, indignation, or hostile engagement rather than inform?",
  },
  {
    id: "reaction_videos",
    label: "Reaction videos",
    description: "Creators mainly reacting to somebody else's content.",
    question: "Is this primarily a reaction video in which the main value is watching a creator react to, comment over, or respond live to someone else's content?",
  },
  {
    id: "pranks",
    label: "Pranks",
    description: "Practical jokes, social experiments, and staged public antics.",
    question: "Is this video primarily a prank, practical joke, social experiment, or staged public stunt intended for entertainment?",
  },
  {
    id: "viral_trends",
    label: "Viral trends and memes",
    description: "Trend recaps, meme compilations, and disposable viral moments.",
    question: "Is this video primarily about a viral trend, meme compilation, internet challenge, or disposable viral moment?",
  },
  {
    id: "ai_slop",
    label: "AI-generated slop",
    description: "Low-effort, mass-produced synthetic narration or imagery.",
    question: "Does this appear to be primarily low-effort, mass-produced AI-generated content, such as synthetic narration over generic imagery, repetitive generated stories, or automated content-farm material?",
  },
  {
    id: "clickbait_listicles",
    label: "Clickbait and listicles",
    description: "Sensational countdowns, reveals, and curiosity-gap content.",
    question: "Is this video primarily a sensational clickbait listicle, countdown, shocking reveal, or curiosity-gap video with little substantive purpose beyond keeping viewers watching?",
  },
  {
    id: "shorts_compilations",
    label: "Short-form compilations",
    description: "Reposted Shorts, TikToks, Reels, and rapid clip compilations.",
    question: "Is this video primarily a compilation or repost of short-form vertical clips such as YouTube Shorts, TikToks, or Instagram Reels?",
  },
  {
    id: "podcast_clips",
    label: "Podcast clips",
    description: "Short excerpts cut from podcasts or long interviews.",
    question: "Is this video primarily a short excerpt or highlight cut from a podcast or long-form interview?",
  },
  {
    id: "true_crime",
    label: "True crime",
    description: "Real crimes, murder cases, and criminal investigations as entertainment.",
    question: "Is this video primarily true-crime entertainment about real murders, crimes, criminal investigations, or alleged perpetrators?",
  },
  {
    id: "doomscrolling",
    label: "Doomscrolling",
    description: "Sensational catastrophe, collapse, and constant-crisis coverage.",
    question: "Is this video primarily sensational doom content emphasizing catastrophe, societal collapse, imminent disaster, or constant crisis in order to keep viewers anxious?",
  },
  {
    id: "partisan_conflict",
    label: "Partisan political conflict",
    description: "Political team-sport fights, dunks, and outrage cycles.",
    question: "Is this video primarily partisan political conflict, team-sport punditry, political dunks, or outrage about opposing political groups rather than substantive policy explanation?",
  },
  {
    id: "conspiracies",
    label: "Conspiracy theories",
    description: "Unsubstantiated hidden-plot and secret-control claims.",
    question: "Is this video primarily promoting or sensationalizing an unsubstantiated conspiracy theory about hidden plots, secret control, or coordinated deception?",
  },
  {
    id: "graphic_violence",
    label: "Graphic or disturbing content",
    description: "Real violence, severe injury, cruelty, or shocking imagery.",
    question: "Is this video primarily focused on graphic real-world violence, severe injury, cruelty, death, or disturbing imagery?",
  },
  {
    id: "gambling",
    label: "Gambling and betting",
    description: "Casinos, sports betting, loot boxes, and gambling wins.",
    question: "Is this video primarily about gambling, casinos, sports betting, loot boxes, betting strategies, or showcasing gambling wins and losses?",
  },
  {
    id: "crypto_speculation",
    label: "Crypto speculation",
    description: "Token hype, price predictions, and speculative trading.",
    question: "Is this video primarily speculative cryptocurrency hype, token promotion, price prediction, or encouragement to trade crypto for profit?",
  },
  {
    id: "get_rich_quick",
    label: "Get-rich-quick content",
    description: "Passive-income promises, hustle schemes, and easy-money pitches.",
    question: "Is this video primarily promoting a get-rich-quick scheme, effortless passive income, hustle shortcut, or unrealistic easy-money opportunity?",
  },
  {
    id: "luxury_flexing",
    label: "Luxury and wealth flexing",
    description: "Status consumption, mansion tours, and conspicuous wealth.",
    question: "Is this video primarily showcasing luxury goods, mansions, expensive cars, extravagant spending, or personal wealth as status entertainment?",
  },
  {
    id: "shopping_hype",
    label: "Shopping hype and hauls",
    description: "Hauls, must-buy lists, unboxings, and consumption-driven content.",
    question: "Is this video primarily a shopping haul, must-buy list, product hype video, or consumption-focused unboxing intended to drive unnecessary purchases?",
  },
  {
    id: "mukbang_food_challenges",
    label: "Mukbang and food challenges",
    description: "Extreme eating, giant portions, and food stunts.",
    question: "Is this video primarily mukbang, extreme eating, a giant-portion challenge, or a food stunt?",
  },
  {
    id: "diet_body_obsession",
    label: "Diet and body obsession",
    description: "Extreme diets, appearance fixation, and rapid transformations.",
    question: "Is this video primarily promoting extreme dieting, rapid body transformation, appearance obsession, or shame-driven weight and fitness content?",
  },
  {
    id: "dating_gender_wars",
    label: "Dating and gender-war ragebait",
    description: "Hostile men-versus-women discourse and adversarial dating content.",
    question: "Is this video primarily hostile gender-war or adversarial dating content that generalizes about men or women to provoke resentment and conflict?",
  },
  {
    id: "paranormal_sensationalism",
    label: "Paranormal sensationalism",
    description: "Ghost, alien, cryptid, and supernatural claims presented as fact.",
    question: "Is this video primarily sensational paranormal content presenting ghosts, aliens, cryptids, hauntings, or supernatural claims as factual evidence?",
  },
  {
    id: "sports_content",
    label: "Sports",
    description: "Games, highlights, sports news, commentary, and analysis.",
    question: "Is this video primarily about sports, including games, highlights, athletes, sports news, commentary, or analysis?",
  },
  {
    id: "music_content",
    label: "Music videos and performances",
    description: "Official music videos, live performances, and lyric videos.",
    question: "Is this video primarily a music video, recorded musical performance, concert clip, or lyric video?",
  },
  {
    id: "childrens_content",
    label: "Children’s content",
    description: "Videos primarily produced for young children.",
    question: "Is this video primarily produced for young children, including nursery content, toy videos, simple children's animation, or preschool entertainment?",
  },
  {
    id: "asmr_satisfying",
    label: "ASMR and satisfying loops",
    description: "Sensory triggers, repetitive loops, and oddly satisfying footage.",
    question: "Is this video primarily ASMR, sensory-trigger content, repetitive satisfying footage, or an oddly satisfying visual loop?",
  },
];
